[# 158678751] As a Looker embedded_role user, so that I can access dashboards after legacy access_filter_fields are disabled, **update the "filters" in Looker-hmac app to use access_filters and user_attributes.**
ConsultingMD/looker-hmac pull request #1
Opened 2018-10-02 01:51 UTC by ajuvekar

As a Looker embedded_role user, so that I can access dashboards after legacy access_filter_fields are disabled, **update the "filters" in Looker-hmac app to use access_filters and user_attributes.**

[Tracker #158678751](https://www.pivotaltracker.com/story/show/158678751)

2018-10-02 01:54 UTC, ajuvekar commented
@nfoen , @richddr - Please CR.

2018-10-02 04:03 UTC, alexebird commented
Still getting these emails from you all <3

2018-10-02 04:06 UTC, gupsydaisys commented
Lol me too.

On Mon, Oct 1, 2018 at 9:04 PM Alex Bird <notifications@github.com> wrote:

> Still getting these emails from you all <3
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ConsultingMD/looker-hmac/pull/1#issuecomment-426142235>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFT4xVuCCv78h74mfA8Zadrhopif0N_tks5uguWvgaJpZM4XDLyL>
> .
>

2018-10-02 06:04 UTC, soonahn commented
You guys are giving away our secrets...

2018-10-02 06:36 UTC, wenever commented
Lol

On Mon, Oct 1, 2018 at 11:04 PM Justin Ahn <notifications@github.com> wrote:

> You guys are giving away our secrets...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ConsultingMD/looker-hmac/pull/1#issuecomment-426159039>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGJjoRbmW4s2KGsJu0y2DPU6Vk8HYPyUks5ugwIDgaJpZM4XDLyL>
> .
>

2018-10-02 21:06 UTC, nfoen reviewed
Hello everyone! 

@ajuvekar looks good to me. This should go with a PR in black, and we should also bump the version here.

2018-10-02 23:06 UTC, ajuvekar commented
thanks @nfoen.

2018-10-02 23:22 UTC, soonahn commented
@nfoen dinner next time you're in town?

2018-10-03 18:16 UTC, cobbr2 requested changes
Once the code is ready (and it is), this PR needs to be completed by:
* Update the VERSION in lib/.../version.rb
* Pushing the rubygem version of it (there's a Rake task for publishing).
Then we'll need to update the version requirement in `black` to finish that PR up.

2018-10-03 18:16 UTC, cobbr2 commented on lib/grnds/looker/hmac.rb
> +          json_user_attributes = @config[:user_attributes].to_json
How are these set?

2018-10-03 18:19 UTC, cobbr2 commented
And for those of you out there wondering why you get updates... this is a public open-source repo, quite intentionally (we were the source of Looker's ruby example code, IIRC), and Github thinks you're still subscribed to it. Just drop your subscriptions if they're annoying :) Good to hear from you all!

2018-10-03 18:19 UTC, cobbr2 commented on lib/grnds/looker/hmac.rb
> +          json_user_attributes = @config[:user_attributes].to_json
Oh. The caller is responsible for setting them, thus the `black` PR. Thanks, @ajuvekar .

2018-10-03 18:45 UTC, ajuvekar commented
@cobbr2 - Updated the version in lib/.../hmac/version.rb to 0.1.0

2018-10-03 21:51 UTC, nfoen approved these changes

2018-10-03 23:43 UTC, cobbr2 approved these changes

2018-10-04 00:05 UTC, merged